Renderers.Constants = {
 // SOils
  soils_eco_desc: {
    0: "N/A",
    2: "Acadian-Appalachian Alpine Tundra",
    3: "Columbia Plateau Vernal Pool",
    4: "Florida River Floodplain Marsh",
    10: "North-Central Interior Dry Oak Forest and Woodland",
    11: "North-Central Interior Dry-Mesic Oak Forest and Woodland",
    12: "Great Basin Foothill and Lower Montane Riparian Woodland and Shrubland",
    13: "Ozark-Ouachita Mesic Hardwood Forest",
    14: "Edwards Plateau Limestone Shrubland",
    15: "Edwards Plateau Mesic Canyon",
    17: "Sonoran Mid-Elevation Desert Scrub",
    20: "Madrean Oriental Chaparral",
    23: "Great Lakes Wet-Mesic Lakeplain Prairie",
    26: "Southern Ridgeand Valley Calcareous Gladeand Woodland",
    27: "Boreal Jack Pine-Black Spruce Forest",
    28: "Boreal White Spruce-Fir-Hardwood Forest",
    29: "Boreal Aspen-Birch Forest",
    30: "Laurentian Acidic Rocky Outcrop",
    32: "Chihuahuan Mixed Salt Desert Scrub",
    33: "Great Basin Semi-Desert Chaparral",
    34: "North Pacific Montane Grassland",
    35: "Temperate Pacific Subalpine-Montane Wet Meadow",
    36: "Modoc Basalt Flow Vernal Pool",
    38: "Northern Rocky Mountain Montane-Foothill Deciduous Shrubland",
    39: "Columbia Basin Foothill and Canyon Dry Grassland",
    40: "Tamaulipan Arroyo Shrubland",
    41: "Tamaulipan Palm Grove Riparian Forest",
    42: "Tamaulipan Floodplain",
    44: "Tamaulipan Tallgrass Grassland",
    45: "Tamaulipan Clay Grassland",
    46: "Tamaulipan Calcareous Thornscrub",
    47: "Tamaulipan Savanna Grassland",
    48: "Tamaulipan  Mesquite Upland Scrub",
    49: "Tamaulipan Mixed Deciduous Thornscrub",
    50: "Northwestern Great Plains Highland White Spruce Woodland",
    51: "Western Great Plains Riparian",
    52: "Rocky Mountain Foothill Limber Pine-Juniper Woodland",
    53: "California Central Valley  Alkali Sink",
    55: "South Coastal California Vernal Pool",
    56: "Northern California Claypan Vernal Pool",
    57: "Mediterranean California Alkali Marsh",
    58: "California Central Valley Riparian Woodland and Shrubland",
    59: "Mediterranean California Foothill and Lower Montane Riparian Woodland",
    60: "California Mesic Serpentine Grassland",
    61: "California Central Valley and Southern Coastal Grassland",
    63: "Mediterranean California Subalpine Meadow",
    64: "Mediterranean California Alpine Dry Tundra",
    65: "Southern California Oak Woodland and Savanna",
    66: "California Coastal Live Oak Woodland and Savanna",
    67: "California Lower Montane Blue Oak-Foothill Pine Woodland and Savanna",
    68: "California Central Valley Mixed Oak Savanna",
    69: "Southern California Coastal Scrub",
    70: "Northern California Coastal Scrub",
    71: "Northernand Central California Dry-Mesic Chaparral",
    72: "Southern California Dry-Mesic Chaparral",
    73: "California Maritime Chaparral",
    74: "Mediterranean California Mesic Serpentine Woodland and Chaparral",
    75: "California Xeric Serpentine Chaparral",
    76: "California Mesic Chaparral",
    77: "California Montane Woodland and Chaparral",
    78: "Sierra Nevada Alpine Dwarf-Shrubland",
    79: "Mediterranean California Lower Montane Black Oak-Conifer Forest and Woodland",
    80: "California Coastal Closed-Cone Conifer Forestand Woodland",
    81: "California Coastal Redwood Forest",
    82: "Central and Southern California Mixed Evergreen Woodland",
    83: "Mediterranean California Mixed Evergreen Forest",
    84: "California Montane Jeffrey Pine-(Ponderosa Pine) Woodland",
    85: "Klamath-Siskiyou Lower Montane Serpentine Mixed Conifer Woodland",
    86: "Mediterranean California Dry-Mesic Mixed Conifer Forest and Woodland",
    87: "Mediterranean California Mesic Mixed Conifer Forestand Woodland",
    88: "Klamath-Siskiyou Upper Montane Serpentine Mixed Conifer Woodland",
    89: "Mediterranean California Red Fir Forest",
    90: "Sierra Nevada Subalpine Lodgepole Pine Forest and Woodland",
    91: "Northern California Mesic Subalpine Woodland",
    92: "Mediterranean California Subalpine Woodland",
    93: "Mediterranean California Mixed Oak Woodland",
    94: "Mediterranean California Southern Coastal Dune",
    95: "Mediterranean California Northern Coastal Dune",
    96: "Mediterranean California Coastal Bluff",
    98: "Southern California Coast Ranges Cliff and Canyon",
    99: "Central California Coast Ranges Cliff and Canyon",
    100: "Klamath-Siskiyou Cliff and Outcrop",
    101: "Sierra Nevada Cliff and Canyon",
    103: "Mediterranean California Alpine Bedrock and Scree",
    104: "Southern Interior Low Plateau Dry-Mesic Oak Forest",
    112: "South-Central Interior Mesophytic Forest",
    113: "Southern Appalachian Oak Forest",
    114: "North Pacific Maritime Coastal Sand Dune and Strand",
    116: "Temperate Pacific Freshwater Emergent Marsh",
    118: "Willamette Valley Wet Prairie",
    121: "Boreal Depressional Bog",
    123: "North Pacific Lowland Riparian Forest and Shrubland",
    124: "North Pacific Montane Riparian Woodland and Shrubland",
    125: "North Pacific Shrub Swamp",
    128: "Willamette Valley Upland Prairie and Savanna",
    129: "North Pacific Avalanche Chute Shrubland",
    130: "North PacificOak Woodland",
    132: "Boreal White Spruce Forest and Woodland",
    133: "North Pacific Broadleaf Landslide Forest and Shrubland",
    134: "North Pacific Dry Douglas-fir-( Madrone) Forest and Woodland",
    135: "North Pacific Mesic Western Hemlock-Yellow-cedar Forest",
    136: "North Pacific Hypermaritime Western Red-cedar-Western Hemlock Forest",
    137: "North Pacific Hypermaritime Sitka Spruce Forest",
    140: "Southern Rocky Mountain Juniper Woodland and Savanna",
    141: "Rocky Mountain Subalpine-Montane Riparian Woodland",
    142: "Rocky Mountain Subalpine-Montane Riparian Shrubland",
    143: "Rocky Mountain Subalpine Mesic-Wet Spruce-Fir Forest and Woodland",
    144: "Rocky Mountain Subalpine-Montane Mesic Meadow",
    145: "Rocky Mountain Subalpine Dry-Mesic Spruce-Fir Forest and Woodland",
    146: "Southern Rocky Mountain Mesic Montane Mixed Conifer Forest and Woodland",
    147: "Southern Rocky Mountain Montane-Subalpine Grassland",
    148: "Southern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest and Woodland",
    149: "Rocky Mountain Lower Montane-Foothill Shrubland",
    150: "Rocky Mountain Lower Montane-Foothill Riparian Woodland and Shrubland",
    151: "Rocky Mountain Lodgepole Pine Forest",
    152: "Rocky Mountain Subalpine-Montane Limber-Bristlecone Pine Woodland",
    153: "Rocky Mountain GambelOak-Mixed Montane Shrubland",
    154: "Western Great Plains Foothilland Piedmont Grassland",
    155: "Rocky Mountain Alpine Turf",
    156: "Rocky Mountain Cliff, Canyonand Massive Bedrock",
    157: "Rocky Mountain Bigtooth Maple Ravine Woodland",
    158: "Rocky Mountain Aspen Forest and Woodland",
    159: "Rocky Mountain Alpine-Montane Wet Meadow",
    160: "Rocky Mountain Alpine Fell-Field",
    161: "Rocky Mountain Alpine Dwarf-Shrubland",
    162: "Rocky Mountain Alpine Bedrock and Scree",
    163: "Northern Rocky Mountain Subalpine Woodland and Parkland",
    164: "Northern Rocky Mountain Subalpine-Upper Montane Grassland",
    165: "Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest",
    166: "Northern Rocky Mountain Lower Montane Riparian Woodland and Shrubland",
    167: "Northern Rocky Mountain Conifer Swamp",
    168: "Northern Rocky Mountain Mesic Montane Mixed Conifer Forest",
    171: "MadreanUpper Montane Conifer-Oak Forest and Woodland",
    172: "Madrean Pinyon-Juniper Woodland",
    173: "Madrean Lower Montane Pine-Oak Forest and Woodland",
    174: "Madrean Encinal",
    175: "Wyoming Basins Dwarf Sagebrush Shrubland and Steppe",
    176: "Columbia Basin Palouse Prairie",
    177: "Inter-Mountain Basins Volcanic Rockand Cinder Land",
    178: "Inter-Mountain Basins Subalpine Limber-Bristlecone Pine Woodland",
    179: "Inter-Mountain Basins Shale Badland",
    180: "Inter-Mountain Basins Semi-Desert Shrub-Steppe",
    181: "Inter-Mountain Basins Semi-Desert Grassland",
    182: "Inter-Mountain Basins Playa",
    183: "Inter-Mountain Basins Montane Sagebrush Steppe",
    184: "Inter-Mountain Basins Mixed Salt Desert Scrub",
    185: "Inter-Mountain Basins Mat Saltbush Shrubland",
    186: "Inter-Mountain Basins Juniper Savanna",
    188: "Inter-Mountain Basins Greasewood Flat",
    189: "Inter-Mountain Basins Cliffand Canyon",
    190: "Inter-Mountain Basins Big Sagebrush Steppe",
    191: "Inter-Mountain Basins Big Sagebrush Shrubland",
    192: "Inter-Mountain Basins Aspen-Mixed Conifer Forest and Woodland",
    193: "Inter-Mountain Basins Active and Stabilized Dune",
    194: "Great Basin Xeric Mixed Sagebrush Shrubland",
    195: "Great Basin Pinyon-Juniper Woodland",
    196: "Inter-Mountain Basins Curl-leaf Mountain Mahogany Woodland and Shrubland",
    197: "Columbia Plateau Scabland Shrubland",
    198: "Columbia Basin Foothill Riparian Woodland and Shrubland",
    199: "Colorado Plateau Pinyon-Juniper Woodland",
    200: "Colorado Plateau Pinyon-Juniper Shrubland",
    201: "Colorado Plateau Mixed Bedrock Canyon and Tableland",
    202: "Colorado Plateau Blackbrush-Mormon-tea Shrubland",
    203: "Colorado Plateau Mixed Low Sagebrush Shrubland",
    204: "Sonoran Paloverde-Mixed Cacti Desert Scrub",
    205: "Sonoran GraniteOutcrop Desert Scrub",
    206: "Sonora-Mojave Semi-Desert Chaparral",
    207: "Sonora-Mojave Creosotebush-White Bursage Desert Scrub",
    208: "North American Warm Desert Wash",
    209: "North American Warm Desert Volcanic Rockland",
    210: "North American Warm Desert Riparian Woodland and Shrubland",
    211: "North American Warm Desert Riparian Mesquite Bosque",
    214: "Sonora-Mojave Mixed Salt Desert Scrub",
    215: "North American Warm Desert Lower Montane Riparian Woodland and Shrubland",
    216: "Chihuahuan-Sonoran Desert Bottomland and Swale Grassland",
    217: "North American Warm Desert Bedrock Cliff and Outcrop",
    218: "North American Warm Desert Activeand Stabilized Dune",
    219: "North American Warm Desert Badland",
    220: "Mojave Mid-Elevation Mixed Desert Scrub",
    221: "Mogollon Chaparral",
    222: "Chihuahuan Succulent Desert Scrub",
    223: "Chihuahuan Stabilized Coppice Dune and Sand Flat Scrub",
    224: "Chihuahuan Sandy Plains Semi-Desert Grassland",
    225: "Apacherian-Chihuahuan Semi-Desert Grassland and Steppe",
    226: "Chihuahuan Mixed Desertand Thorn Scrub",
    227: "Apacherian-Chihuahuan Mesquite Upland Scrub",
    228: "Chihuahuan Gypsophilous Grassland and Steppe",
    229: "Chihuahuan Creosotebush Desert Scrub",
    230: "Madrean Juniper Savanna",
    231: "North American Arid West Emergent Marsh",
    233: "North-CentralOak Barrens",
    238: "Laurentian-Acadian Northern Pine-(Oak) Forest",
    239: "Laurentian Pine-Oak Barrens",
    240: "Ozark-Ouachita Dry-Mesic Oak Forest",
    241: "Ozark-Ouachita Dry Oak Woodland",
    242: "South-Central Interior Small Streamand Riparian",
    243: "South-Central Interior Large Floodplain",
    245: "Ozark-Ouachita Riparian",
    247: "North-Central Interior Wet Meadow-Shrub Swamp",
    248: "North-Central Interior Wet Flatwoods",
    250: "North-Central Interior Oak Savanna",
    251: "North-Central Interior Maple-Basswood Forest",
    252: "North-Central Interior Sandand Gravel Tallgrass Prairie",
    253: "North-Central Interior Floodplain",
    254: "North-Central Interior Beech-Maple Forest",
    255: "Central Interior Highlands Dry Acidic Glade and Barrens",
    256: "Central Interior Highlands Calcareous Glade and Barrens",
    257: "Central Interior Calcareous Cliff and Talus",
    258: "Central Interior Acidic Cliff and Talus",
    259: "Eastern Great Plains Tallgrass Aspen Parkland",
    260: "Eastern Great Plains Wet Meadow, Prairie, and Marsh",
    261: "Northern Tallgrass Prairie",
    262: "Southeastern Great Plains Tallgrass Prairie",
    263: "Southern Blackland Tallgrass Prairie",
    264: "Central Tallgrass Prairie",
    265: "Crosstimbers Oak Forest and Woodland",
    266: "Northwestern Great Plains Aspen Forest and Parkland",
    267: "Western Great Plains Wooded Drawand Ravine",
    268: "Western Great Plains Floodplain",
    269: "Northwestern Great Plains Riparian",
    270: "Northwestern Great Plains Floodplain",
    271: "Western Great Plains Open Freshwater Depression Wetland",
    272: "Northwestern Great Plains Mixedgrass Prairie",
    273: "Western Great Plains Tallgrass Prairie",
    274: "Western Great Plains Shortgrass Prairie",
    275: "Western Great Plains Sandhill Steppe",
    276: "Western Great Plains Sand Prairie",
    278: "Western Great Plains Mesquite Woodland and Shrubland",
    279: "Western Great Plains Dry Bur Oak Forest and Woodland",
    280: "Western Great Plains Closed Depression Wetland",
    281: "Western Great Plains Cliffand Outcrop",
    282: "Southwestern Great Plains Canyon",
    283: "Western Great Plains Badlands",
    284: "Northwestern Great Plains Shrubland",
    285: "Great Plains Prairie Pothole",
    286: "Edwards Plateau Limestone Savanna and Woodland",
    287: "Central Mixedgrass Prairie",
    288: "Central Appalachian Stream and Riparian",
    289: "Central Appalachian River Floodplain",
    290: "North-Central Appalachian Seepage Fen",
    291: "North-Central Interior and Appalachian Acidic Peatland",
    292: "North-Central Interior and Appalachian Rich Swamp",
    293: "North-Central Appalachian Acidic Swamp",
    294: "North-Central Appalachian Circumneutral Cliffand Talus",
    295: "Central Appalachian Alkaline Glade and Woodland",
    297: "Central Appalachian Pine-Oak Rocky Woodland",
    298: "Appalachian Shale Barrens",
    299: "Centraland Southern Appalachian Montane Oak Forest",
    300: "Appalachian( Hemlock)-Northern Hardwood Forest",
    301: "Northeastern Interior Dry-Mesic Oak Forest",
    302: "Central Appalachian Dry Oak-Pine Forest",
    303: "Northeastern Interior Pine Barrens",
    304: "Eastern Boreal Floodplain",
    305: "Laurentian-Acadian Floodplain Forest",
    309: "Boreal-Laurentian Bog",
    311: "Acadian Estuary Marsh",
    313: "Acadian-Appalachian Conifer Seepage Forest",
    314: "Laurentian-Acadian Alkaline Conifer-Hardwood Swamp",
    315: "Northern Appalachian-Acadian Conifer-Hardwood Acidic Swamp",
    317: "Laurentian-Acadian Calcareous Rocky Outcrop",
    318: "Northern Appalachian-Acadian Rocky Heath Outcrop",
    320: "Laurentian-Acadian Acidic Cliff and Talus",
    321: "Acadian-Appalachian Subalpine Woodland and Heath-Krummholz",
    322: "Acadian-Appalachian Montane Spruce-Fir Forest",
    323: "Acadian Low-Elevation Spruce-Fir-Hardwood Forest",
    324: "Laurentian-Acadian Northern Hardwoods Forest",
    325: "Laurentian-Acadian Pine-Hemlock-Hardwood Forest",
    326: "AcadianNear-Boreal Spruce Flat",
    328: "Southern Coastal Plain Dry Upland Hardwood Forest",
    329: "East Gulf Coastal Plain Small Stream and River Floodplain Forest",
    331: "East Gulf Coastal Plain Southern Loblolly-Hardwood Flatwoods",
    332: "East Gulf Coastal Plain Southern Loess Bluff Forest",
    333: "East Gulf Coastal Plain Jackson Prairie and Woodland",
    336: "Lower Mississippi Alluvial Plain Grand Prairie",
    337: "West Gulf Coastal Plain Nonriverine Wet Hardwood Flatwoods",
    345: "South Texas Sand Sheet Grassland",
    349: "Panhandle Florida Limestone Glade",
    350: "Lower Mississippi River Dune Woodland and Forest",
    351: "Northern Atlantic Coastal Plain Basin Peat Swamp",
    352: "Northern Atlantic Coastal Plain Basin Swamp and Wet Hardwood Forest",
    357: "Florida Big Bend Saltand Brackish Tidal Marsh",
    359: "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest",
    362: "Southern Coastal Plain Limestone Forest",
    363: "Southern Coastal Plain Hydric Hammock",
    365: "Atlantic Coastal Plain Xeric River Dune",
    366: "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland",
    367: "Southern Coastal Plain Sinkhole",
    368: "Southern Coastal Plain Oak Dome and Hammock",
    369: "Southern Coastal Plain Blackwater River Floodplain Forest",
    371: "Central Florida Wet Prairieand Herbaceous Seep",
    375: "West Gulf Coastal Plain Small Stream and River Forest",
    378: "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest",
    379: "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland",
    380: "East Gulf Coastal Plain Northern Loess Bluff Forest",
    381: "South-Central Interior/Upper Coastal Plain Wet Flatwoods",
    382: "South-Central Interior/Upper Coastal Plain Flatwoods",
    384: "East Gulf Coastal Plain Northern Mesic Hardwood Slope Forest",
    386: "Northern Atlantic Coastal Plain Hardwood Forest",
    389: "Mississippi Delta Salt and Brackish Tidal Marsh",
    395: "Central and Upper Texas Coast Dune and Coastal Grassland",
    397: "Texas Coastal Bend Beach",
    398: "South Texas Lomas",
    402: "Southern Ridge and Valley/Cumberland Dry Calcareous Forest",
    403: "Southern Ridge and Valley Patch Prairie",
    404: "Southern Piedmont Cliff",
    405: "East Gulf Coastal Plain Interior Shrub Bog",
    408: "Central Florida Pine Flatwoods",
    409: "South Florida Pine Flatwoods",
    411: "West Gulf Coastal Plain Southern Calcareous Prairie",
    412: "West Gulf Coastal Plain Pine-Hardwood Forest",
    413: "West Gulf Coastal Plain Northern Calcareous Prairie",
    416: "Northern Atlantic Coastal Plain Pitch Pine Lowland",
    417: "Southernand Central Appalachian Cove Forest",
    422: "Southwest Florida Coastal Strandand Maritime Hammock",
    423: "South Florida Pine Rockland",
    425: "South Florida Cypress Dome",
    428: "Allegheny-Cumberl and Dry Oak Forest and Woodland",
    429: "Southern Interior Sinkhole Wall",
    430: "Southern Interior Calcareous Cliff",
    431: "Pennyroyal Karst Plain Prairie and Barrens",
    432: "Eastern Highland Rim Prairie and Barrens",
    433: "East Gulf Coastal Plain Jackson Plain Prairie and Barrens",
    435: "Southern and Central Appalachian Mafic Glade and Barrens",
    438: "Southern Piedmont Mesic Forest",
    439: "Southern Piedmont Dry Oak-(Pine) Forest",
    440: "Alabama Ketona Glade and Woodland",
    441: "Cumberland Sandstone Glade and Barrens",
    442: "Piedmont Upland Depression Swamp",
    443: "Nashville Basin Limestone Glade and Woodland",
    444: "Southern Appalachian Low-Elevation Pine Forest",
    445: "Southern Appalachian Montane Pine Forest and Woodland",
    446: "Southern Appalachian Montane Cliff and Talus",
    448: "Southern Piedmont Gladeand Barrens",
    451: "Southern Piedmont Small Floodplain and Riparian Forest",
    453: "Southeastern Interior Longleaf Pine Woodland",
    454: "Southern Appalachian Seepage Wetland",
    455: "Ouachita Novaculite Glade and Woodland",
    456: "Ozark-Ouachita Shortleaf Pine-Oak Forest and Woodland",
    457: "Arkansas Valley Prairie and Woodland",
    458: "Cumberland Acidic Cliff and Rockhouse",
    459: "Ouachita Montane Oak Forest",
    466: "Piedmont Seepage Wetland",
    467: "Southern Appalachian Granitic Dome",
    468: "Southern Appalachian Grass and Shrub Bald",
    469: "West Gulf Coastal Plain Upland Longleaf Pine Forest and Woodland",
    473: "Southern Appalachian Spray Cliff",
    474: "South Florida Hardwood Hammock",
    475: "South Florida Everglades Sawgrass Marsh",
    476: "Florida Longleaf Pine Sandhill",
    477: "Northern Atlantic Coastal Plain Tidal Swamp",
    478: "Atlantic Coastal Plain Upland Longleaf Pine Woodland",
    479: "West Gulf Coastal Plain Mesic Hardwood Forest",
    480: "West Gulf Coastal Plain Pine-Hardwood Flatwoods",
    487: "Northern Atlantic Coastal Plain Pitch Pine Barrens",
    488: "Piedmont Hardpan Woodland and Forest",
    489: "Atlantic Coastal Plain Peatland Pocosin and Canebrake",
    494: "Central Atlantic Coastal Plain Maritime Forest",
    499: "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland",
    501: "Atlantic Coastal Plain Streamhead Seepage Swamp, Pocosin,and Baygall",
    502: "Southern Coastal Plain Nonriverine Cypress Dome",
    503: "Atlantic Coastal Plain Small Brownwater River Floodplain Forest",
    508: "Atlantic Coastal Plain Mesic Hardwood Forest",
    509: "Atlantic Coastal Plain Dryand Dry-Mesic Oak Forest",
    511: "West Gulf Coastal Plain Herbaceous Seepage Bog",
    513: "West Gulf Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    516: "Florida Peninsula Inland Scrub",
    517: "West Gulf Coastal Plain Sandhill Oakand Shortleaf Pine Forest and Woodland",
    518: "Southern Rocky Mountain Pinyon-Juniper Woodland",
    520: "Laurentian-Acadian Wet Meadow-Shrub Swamp",
    521: "Laurentian-Acadian Freshwater Marsh",
    522: "Inter-Mountain Basins Alkaline Closed Depression",
    524: "South Florida Hydric Hammock",
    525: "North-Central Interior Freshwater Marsh",
    527: "North Pacific Maritime Dry-Mesic Douglas-fir-Western Hemlock Forest",
    528: "North Pacific Maritime Mesic-Wet Douglas-fir-Western Hemlock Forest",
    530: "Columbia Plateau Low Sagebrush Steppe",
    531: "Columbia Plateau Ashand Tuff Badland",
    532: "Columbia Plateau Western Juniper Woodland and Savanna",
    534: "Columbia Plateau Silver Sagebrush Seasonally Flooded Shrub-Steppe",
    535: "East Cascades Oak-Ponderosa Pine Forest and Woodland",
    536: "East Cascades Mesic Montane Mixed-Conifer Forest and Woodland",
    537: "Northern Rocky Mountain Western Larch Savanna",
    538: "Northern Rocky Mountain Ponderosa Pine Woodland and Savanna",
    542: "North Pacific Alpineand Subalpine Bedrock and Scree",
    543: "North Pacific Wooded Volcanic Flowage",
    544: "North Pacific Montane Shrubland",
    545: "North Pacific Hypermaritime Shruband Herbaceous Headland",
    546: "North Pacific Herbaceous Baldand Bluff",
    547: "North Pacific Hardwood-Conifer Swamp",
    553: "North Pacific Volcanic Rockand Cinder Land",
    554: "North Pacific Montane Massive Bedrock, Cliffand Talus",
    555: "North Pacific Coastal Cliffand Bluff",
    557: "North Pacific Mesic Western Hemlock-Silver Fir Forest",
    558: "North Pacific Dry-Mesic Silver Fir-Western Hemlock-Douglas-fir Forest",
    559: "North Pacific Alpineand Subalpine Dry Grassland",
    560: "Northern Rocky Mountain Lower Montane, Foothill and Valley Grassland",
    561: "Llano Uplift Acidic Forest, Woodland and Glade",
    563: "Northern Rocky Mountain Foothill Conifer Wooded Steppe",
    564: "Middle Rocky Mountain Montane Douglas-fir Forest and Woodland",
    565: "Rocky Mountain Poor-Site Lodgepole Pine Forest",
    566: "Northern Rocky Mountain Subalpine Deciduous Shrubland",
    568: "Sierran-Intermontane Desert Western White Pine-White Fir Woodland",
    569: "Klamath-Siskiyou Xeromorphic Serpentine Savanna and Chaparral",
    570: "Southeastern Great Plains Floodplain Terrace",
    571: "Edwards Plateau Riparian",
    572: "Edwards Plateau Upland Depression",
    573: "Edwards Plateau Carbonate Glade and Barrens",
    574: "Edwards Plateau Dry-Mesic Slope Forest and Woodland",
    575: "Edwards Plateau Cliff",
    577: "Chihuahuan Loamy Plains Desert Grassland",
    578: "Northwestern Great Plains-Black Hills Ponderosa Pine Woodland and Savanna",
    579: "Southern Rocky Mountain Ponderosa Pine Woodland",
    580: "Southern Rocky Mountain Ponderosa Pine Savanna",
    582: "Ozark-Ouachita Shortleaf Pine-Bluestem Woodland",
    583: "Ozark Prairieand Woodland",
    584: "Southern Crowley's Ridge Mesic Loess Slope Forest",
    585: "Mississippi River Alluvial Plain Dry-Mesic Loess Slope Forest",
    586: "Northern Crowley's Ridge Sand Forest",
    589: "East-Central Texas Plains Post Oak Savanna and Woodland",
    590: "West Gulf Coastal Plain Stream Terrace Sandyland Longleaf Pine Woodland",
    600: "Water",
    601: "Unknown - pixel count > 20,000",
    602: "Unknown - pixel count <= 20,000",
  },
};
